### ISSUE TITLE
Permission Denied in Android 10

### ISSUE THREAD

**Issue by SpartanzRaj** [a914-gowtham/Android-video-trimmer#1]
Receiving permission denied error in Android 10 : java.io.IOException: Cannot run program "/data/user/0/com.gowtham.videotrimmer/files/ffmpeg": error=13, Permission denied.

But working fine in below version of android 10

**Comment by a914-gowtham** [comment]
thanks for the first issue.will be fixed by tommorrow

**Comment by SpartanzRaj** [comment]
I replaced FFmpeg library with this new library https://github.com/tanersener/mobile-ffmpeg, Now it is working. But the problem is it supports currentMinSDK as 24

**Comment by a914-gowtham** [comment]
i checked these LTS versions of mobile-ffmpeg 4.2.2.LTS and 4.3.1.LTS doesn't have this issue.let you know once i worked with this

**Comment by a914-gowtham** [comment]
Use this latest version 1.0.5

**Comment by a914-gowtham** [comment]
You can reopen this issue.if,you get error
