### ISSUE TITLE
cannot find symbol import com.gowtham.library.utils.TrimmerConstants;

### ISSUE THREAD

**Issue by alapputatunda** [a914-gowtham/Android-video-trimmer#10]
Why I am getting this while building my project? Please help me!

**Comment by a914-gowtham** [comment]
I have updated the library.use the latest version  implementation 'com.github.a914-gowtham:Android-video-trimmer:1.4.0'

**Comment by VIVEKCODEXP** [comment]
I am getting an unresolved reference "import com.gowtham.library.utils.TrimVideo" on main activity. I have tried the latest version as well as 1.7.0 - 1.7.1 and 1.4.0 as well and build all of them successfully but cant import the TrimVideo in my main activity. Is it something that I am not doing correctly?
