### ISSUE TITLE
Show message "Storage permission denied" on android 13 and 14

### ISSUE THREAD

**Issue by HanhVoS3Corp** [a914-gowtham/android-video-trimmer#101]
Hi everyone, I faced issue related storage permission when trimming video on android 13 and android 14. 
Step reproduces:
1. I request needed permissions: 
android 13: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, ACCESS_MEDIA_LOCATION
android 14: READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, ACCESS_MEDIA_LOCATION, READ_MEDIA_VISUAL_USER_SELECTED
2. I choosed a video from storage, get uri of that video.
3. I used the lib to open Trimmer Video screen like this: 
TrimVideo.activity(mediaPath).start(controller, trimmerVideoActivityResult)
6. The app show message "Storage permission denied"
![image](https://github.com/a914-gowtham/android-video-trimmer/assets/155606453/374e2975-4843-404e-bca7-2df69d4c5db3)

After that, I opened the source code of the library and found that the lib check READ_EXTERNAL_STORAGE and ACCESS_MEDIA_LOCATION for android 10 or higher. This way is not okay for android 13 and 14.
![image](https://github.com/a914-gowtham/android-video-trimmer/assets/155606453/0ce16920-bddb-4468-a1ec-cf5187a0661e)

Library version: 1.7.3

Please team help me this case, thanks.

**Comment by a914-gowtham** [comment]
@HanhVoS3Corp Hi, i think ACCESS_MEDIA_LOCATION is not needed for this library as it is used to fetch meta like latlng(location) of image/video.

so, i will remove it and will share a build version here.

**Comment by a914-gowtham** [comment]
@HanhVoS3Corp  fixed in [17.18](https://github.com/a914-gowtham/android-video-trimmer/releases/tag/1.7.18)

**Comment by a914-gowtham** [comment]
I just noticed the library version you mentioned. seems like in that version android 13 permission changes were not handled.

use the latest version

**Comment by HanhVoS3Corp** [comment]
Thanks for helping. Have a good day !
