### ISSUE TITLE
Not support permission "android.permission.READ_MEDIA_VISUAL_USER_SELECTED" on android 14

### ISSUE THREAD

**Issue by vnhanh** [a914-gowtham/android-video-trimmer#102]
Hi team,
First, I would like to thank your team for quick support in this issue: https://github.com/a914-gowtham/android-video-trimmer/issues/101.

For now, I raise new issue related to new permission READ_MEDIA_VISUAL_USER_SELECTED on Android 14. This new permission was wrote in this link: https://developer.android.com/about/versions/14/changes/partial-photo-video-access.

Version: 1.7.15.
Step by step:
1.  On Android 14, user tap Add Photo button, my app shows the Permission Request dialog. 
2. User allow "Choose Photos and Videos" permission, user select videos of their preference, so my app using the library to trim video.

Expected result: my app show the Trim video screen.
Actual result: my app can't not show the Trim video screen and show failed message.

After that, I checked code and saw that the library's code not support the permission **_android.permission.READ_MEDIA_VISUAL_USER_SELECTED_**:
![image](https://github.com/a914-gowtham/android-video-trimmer/assets/22546252/f0879385-bc52-4f6a-a213-feff91ee4a7f)
Image 1. The library's code with version 1.7.15 not support checking permission READ_MEDIA_VISUAL_USER_SELECTED on android 14.

![image](https://github.com/a914-gowtham/android-video-trimmer/assets/22546252/19489af4-1fbb-4b65-8adb-11d0abd50010)
**Image 2.** Request permission dialog on android 14

I tried to update the latest version 1.7.18, but the issue still exist.
![image](https://github.com/a914-gowtham/android-video-trimmer/assets/22546252/607c9171-cc97-47a7-a9a1-c4e7b53f1a2a)
Image 3. The library's code on version 1.7.18

Please help me, thanks very much!

**Comment by a914-gowtham** [comment]
Hi @vnhanh  fixed in 1.7.19.

**Comment by vnhanh** [comment]
Hi @a914-gowtham thanks very much! Have a nice day!
