### ISSUE TITLE
Failed to trim issue

### ISSUE THREAD

**Issue by sumonshil** [a914-gowtham/Android-video-trimmer#15]
![Screenshot_20201005-213947](https://user-images.githubusercontent.com/72403670/95104343-53877b80-0753-11eb-848d-787985f555cc.png)
When click on done button for trim result ,it always show me failed to trim . please give me a solution

**Comment by a914-gowtham** [comment]
Could you please send error log

**Comment by a914-gowtham** [comment]
and share the code for opening the trimming screen

**Comment by sumonshil** [comment]
**// log error**.....................
`2020-10-06 14:08:56.530 2915-7681/com.magica_technology.icon E/mobile-ffmpeg: /storage/emulated/0/Download/trimmed_video_0.mp4: Permission denied
2020-10-06 14:08:56.561 2915-7681/com.magica_technology.icon E/mobile-ffmpeg: /storage/emulated/0/Download/trimmed_video_0.mp4: Permission denied
2020-10-06 14:08:56.568 1231-3841/? E/InputDispatcher: Window handle Window{43f7d54 u0 com.magica_technology.icon/com.gowtham.library.ui.ActVideoTrimmer} has no registered input channel
2020-10-06 14:08:56.585 1231-3841/? E/InputDispatcher: Window handle Window{43f7d54 u0 com.magica_technology.icon/com.gowtham.library.ui.ActVideoTrimmer} has no registered input channel
`

//**code**..........................................

`  

 @Override
    
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_post_video);
        init();
        storage= FirebaseStorage.getInstance();
        storageReference = storage.getReference();

        vUri =getIntent().getStringExtra("Uri");
        TrimVideo.activity(vUri)
                .setTrimType(TrimType.MIN_MAX_DURATION)
                .setAccurateCut(true)
                .setCompressOption(new CompressOption())
                .setMinToMax(10, 180)  //seconds
                .start(PostVideoActivity.this);

    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == TrimVideo.VIDEO_TRIMMER_REQ_CODE && data != null) {
            Uri uri = Uri.parse(TrimVideo.getTrimmedVideoPath(data));
        }
    }
`

**Comment by a914-gowtham** [comment]
Have you given `        android:requestLegacyExternalStorage="true"
`  this AndroidManifest.class inside application class.and you have to use provider in your manifest [REFER THIS](https://github.com/a914-gowtham/Android-video-trimmer/blob/master/app/src/main/AndroidManifest.xml)

**Comment by sumonshil** [comment]
Thank you 
Problem solved
