### ISSUE TITLE
failed to return result to fragment

### ISSUE THREAD

**Issue by RanjeethKumar55** [a914-gowtham/Android-video-trimmer#20]
when i tried to trim video from a fragment the result is not being returned to the fragment. Please do replay , i will be so happy if i get the replay back soon

**Comment by a914-gowtham** [comment]
Trimmed video url will be passed to activity result.You could pass it to fragment activity result like below
```
    @Override           //Activity result
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        fHome.onActivityResult(requestCode, resultCode, data);  //to fragment 
}
```

**Comment by RanjeethKumar55** [comment]
thank you so much
