### ISSUE TITLE
Implememt library in fragment

### ISSUE THREAD

**Issue by pserdax** [a914-gowtham/Android-video-trimmer#21]
Hello,
Thanks for great lib. The lib doesn't work properly when I implement it in fragment. Do you have any idea about this issue?
Thanks

**Comment by pserdax** [comment]
Or have you ever implemented the lib in fragment? If yes, do i have any chance to check it out?
Thanks

**Comment by pserdax** [comment]
This issue will be solved when you make a new release by including the following change:
 https://github.com/a914-gowtham/Android-video-trimmer/commit/516ac64c9b53dd49f25f4d2fb31b6f09b0d38e5f

**Comment by a914-gowtham** [comment]
You can use the latest version

**Comment by pserdax** [comment]
Thanks a lot for release!
