### ISSUE TITLE
Translation required for "Edit Video" title in video editor. 

### ISSUE THREAD

**Issue by pranishres** [a914-gowtham/Android-video-trimmer#22]
I have been using this library and found it as the best one for development and support from you guys. However, I have 1 change request. 

My app is multilingual and when I build it in Japanese, the title of the video editor is still "Edit Vide" which is hardcoded in `ActVideoTrimmer` class. Could you migrate the hardcoded texts to strings file so that I can add translations for other languages as well?

**Comment by a914-gowtham** [comment]
Ok..will be added for the next release

**Comment by pranishres** [comment]
> Ok..will be added for the next release

Thank you. How long will it take for the next release? I am in need of it in a day or two. So can I just copy all the library code to my project? Do I have your permission?

**Comment by a914-gowtham** [comment]
Sure...you can use it.

**Comment by pranishres** [comment]
> Sure...you can use it or else you can even make a pull request

Hello again. I would be glad if you could you do a quick fix and update the library by adding the hardcoded text to strings.xml file? I have release my app to playstore and don't want to take risk by manually adding all your code.

**Comment by a914-gowtham** [comment]
I just made a release.Use that

**Comment by pranishres** [comment]
Thank you. You are the best. You are the one who have provided me this much support in GitHub till now.
