### ISSUE TITLE
Support for Latest ExoPlayer Version

### ISSUE THREAD

**Issue by MujammilAhamed** [a914-gowtham/Android-video-trimmer#23]
-CreateMediaSource, ExoPlayerFactory Instance, DefaultEventListener are deprecated

Need an update with latest ExoPlayer(2.12.1)

**Comment by a914-gowtham** [comment]
Thanks for the issue.will be updated in next release

**Comment by a914-gowtham** [comment]
Use the latest version 
`implementation 'com.github.a914-gowtham:Android-video-trimmer:1.4.3'`

**Comment by a914-gowtham** [comment]
Use the latest version 
`   implementation 'com.github.a914-gowtham:Android-video-trimmer:1.4.4'
`
