### ISSUE TITLE
How to trim video without showing range selection?

### ISSUE THREAD

**Issue by surajpunemaha** [a914-gowtham/Android-video-trimmer#25]
I want to trim video without providing UI for range selection. Is it possible? if yes how?

**Comment by a914-gowtham** [comment]
Sorry, you can't do that. it makes no sense to this trimming lib. you can only hide the controller seek bar by using the below snippet. or else you could pull the code and make changes for your requirement.
```
TrimVideo.activity(String.valueOf(videoUri))
          .setHideSeekBar(true)
          .start(this);
```
