### ISSUE TITLE
AAPT: error

### ISSUE THREAD

**Issue by Tarikmnk** [a914-gowtham/Android-video-trimmer#26]
Hi,
I encountered four errors.

1-)  xmlns:ns1="urn:oasis:names:tc:xliff:document:1.2" xmlns:ns2="http://schemas.android.com/tools"
2-) duplicate value for resource 'attr/position' with config ''.
3-) resource previously defined here.
4-) duplicate value for resource 'attr/data_type' with config ''.

ı used version is 1.5.2.

Help me :)

**Comment by a914-gowtham** [comment]
Can you explain the reproduce steps?

**Comment by Tarikmnk** [comment]
ı just write this code 
        TrimVideo.activity(sendDataPath)
            .setCompressOption(CompressOption ())
            .setHideSeekBar(true)
            .setDestination(video.path)
            .start(this)

when ı start build , my app is not build.

**Comment by Tarikmnk** [comment]
This errors are in crystal:crystalrangeseekbar

**Comment by Tarikmnk** [comment]
when I downloaded this code and crystal:crystalrangeseekbar. After I put in my project and problems solved. This library very good but I changed one code block. I changed this code;

<img width="706" alt="Screen Shot 2020-12-12 at 14 29 35" src="https://user-images.githubusercontent.com/46998249/101982908-335ec600-3c88-11eb-9471-9942d2b2cf12.png">

because the user can select 60 intervals in the video I want.

do you want to Pull Request my push?

**Comment by a914-gowtham** [comment]
Thanks for your contribution. Your fix will be available from the next release.
