### ISSUE TITLE
Updation: Validation for minGap

### ISSUE THREAD

**Issue by rahul4452** [a914-gowtham/Android-video-trimmer#3]
Hello, @a914-gowtham great work. Just one query or you can say update that there is no message on minGap like when users add video less than the required minGap. 

Thanks for this work.

**Comment by a914-gowtham** [comment]
you could validate video duration using this snippet before you open the trimmer activitity             
  //check video duration if needed
                if (TrimmerUtils.getVideoDuration(this,data.getData())<=30){
                    Toast.makeText(this,"Video duration should be larger than 30 sec",Toast.LENGTH_SHORT).show();
                }else{
                         Intent intent=new Intent(this,ActVideoTrimmer.class);
                         intent.putExtra(TrimmerConstants.TRIM_VIDEO_URI,String.valueOf(videoUri));
                         intent.putExtra(TrimmerConstants.TRIM_TYPE,0); //optional: it will take by default
                         startActivityForResult(intent,TrimmerConstants.REQ_CODE_VIDEO_TRIMMER);
}

**Comment by rahul4452** [comment]
Thanks, @a914-gowtham for the solution.
