### ISSUE TITLE
Storage permission is missing toast message on Android 11

### ISSUE THREAD

**Issue by qwaskhaled** [a914-gowtham/Android-video-trimmer#38]
I can't trim the video because WRITE_STORAGE_PERMission always returns false.

**Comment by qwaskhaled** [comment]
You may consider context.getExternalFilesDir() because writing to it doesn't need permission

**Comment by a914-gowtham** [comment]
Hey @qwaskhaled  besides this storage issue current version of the library a [issue on release build](https://github.com/a914-gowtham/Android-video-trimmer/issues/35#issuecomment-798870992) because of the dependent library. consider using https://github.com/a914-gowtham/videotrimmer this repo

**Comment by a914-gowtham** [comment]
> You may consider context.getExternalFilesDir() because writing to it doesn't need permission

I've worked on this storage issue in the new repository that I mentioned above. I will check your suggestion and update that  new repository soon

**Comment by qwaskhaled** [comment]
Where I can find the new repository ?

**Comment by a914-gowtham** [comment]
https://github.com/a914-gowtham/videotrimmer

**Comment by qwaskhaled** [comment]
I tried it and it's fixed. Also it's very difficult to setup so I would really appreciate if you can stick to this repo

**Comment by a914-gowtham** [comment]
@qwaskhaled  can you try now I just worked on changes in both library, that new repo and  made a release

**Comment by qwaskhaled** [comment]
Yes, it's working now. Thank very much for your assistance and I do appreciate your fast response.

**Comment by a914-gowtham** [comment]
@qwaskhaled  use can use the latest release that release build issue has been resolved now.
