### ISSUE TITLE
Video stretched after trimming 

### ISSUE THREAD

**Issue by braver-tool** [a914-gowtham/Android-video-trimmer#46]
I facing a video stretch issue after trimming the video. It does not occur for all video files, only occurs on some videos. I found one thing for the issue, that is height and width of the video are interchanged, also rotation is changed, after executing the below lines. 
	I've attached a sample video file. The actual width and height are 352 and 640, after trimming the changed as 640 and 340. Please help to fix the issue.

       `MediaMetadataRetriever metaRetriever = new MediaMetadataRetriever();
        metaRetriever.setDataSource(String.valueOf(uri));
        String height = metaRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT);
        String width = metaRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH);
        String rotation = retriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION);
        int w = TrimmerUtils.clearNull(width).isEmpty() ? 0 : Integer.parseInt(width);
        int h = Integer.parseInt(height);`

https://user-images.githubusercontent.com/49281317/116427818-fd4e6700-a861-11eb-8cac-9bf9535b209f.mp4

**Comment by a914-gowtham** [comment]
Can you share the trimOption that you used

**Comment by braver-tool** [comment]
Am not using any compressOption, TrimOption for that. I just use default options for all like below,
` TrimVideo.activity(data).setCompressOption(new CompressOption()).start(this);`

**Comment by a914-gowtham** [comment]
Thanks for creating a good issue. It occurs when we try to trim a video that has rotation 90 || 360. I was passing width and height in the ffmpeg command and that's where had to make changes. It has been fixed in the latest release. you could use the `   implementation 'com.github.a914-gowtham:Android-video-trimmer:1.6.4'
`

**Comment by a914-gowtham** [comment]
@braver-tool  feel free to open this issue if it does happen again.

**Comment by VivekThummar52** [comment]
i just want to ask you one question, don't you think that rotation check will be for `90` and `270`, if i'm wrong than please explain me why `90` and `360`?

**Comment by a914-gowtham** [comment]
My bad. that should be 270.

**Comment by a914-gowtham** [comment]
@braver-tool @VivekThummar52  thanks for mentioning it. I don't know how I was careless. Use this latest version
```gradle
implementation 'com.github.a914-gowtham:Android-video-trimmer:1.6.5'
```
