### ISSUE TITLE
The video is not cutting by 30seconds based onn FIXED_GAP_DURATION

### ISSUE THREAD

**Issue by Dangujba** [a914-gowtham/Android-video-trimmer#5]
I try to use fixed gap duration by 30 sec so that it can trim by 30 no matter where you seelect is not working.

**Comment by a914-gowtham** [comment]
can you please send the intent data which you sent to the trimmerActivity

**Comment by a914-gowtham** [comment]
this is the correct snippet to use fixedgap
`      startActivityForResult(new Intent(this, ActVideoTrimmer.class)
                            .putExtra(TrimmerConstants.HIDE_PLAYER_SEEKBAR, true)
                            .putExtra(TrimmerConstants.TRIM_VIDEO_URI, String.valueOf(your video uri))
                            .putExtra(TrimmerConstants.TRIM_TYPE, 1)
                            .putExtra(TrimmerConstants.FIXED_GAP_DURATION, 30L),
                    TrimmerConstants.REQ_CODE_VIDEO_TRIMMER);`

**Comment by Dangujba** [comment]
I tried the given code it doesn't working still.
Description of the problem in details
I am working in 1 App i want to add feature like WhatsApp video trimmer, which no matter where you moved the range selection icon the range will stay between 30 seconds, and the FIXED_GAP_DURATION is working normal, the problem is that after getting the results of the video then found out that the trimmed video length is more than 30 seconds. Sometimes the output length is 2minutes+ i think it given the results based on length of the video because the video i used to test are having length of 5 and 30seconds+ so it seems like it calculating something like 30 * video minutes. What is the solution?

**Comment by a914-gowtham** [comment]
thanks for the explanation...it will be solved by tonight

**Comment by Dangujba** [comment]
Okay let me be informed when you fixed it. And Please i am asking for some features such as adding Caption and some editing features. Thanks

**Comment by a914-gowtham** [comment]
send me a mail to gowtham6672@gmail.com with your requirements .i try to make it if possible

**Comment by Dangujba** [comment]
Sir, have you fixed the bug?

**Comment by a914-gowtham** [comment]
yea use this   implementation 'com.github.a914-gowtham:Android-video-trimmer:1.2.0'

**Comment by Dangujba** [comment]
Good Sir, Is now working perfectly. If it is possible it need improvement, because the trimming take much longer time sometime it can take up 80 seconds or 2 minute. Thanks

**Comment by a914-gowtham** [comment]
that's a temporary solution.here's the solution implementation 'com.github.a914-gowtham:Android-video-trimmer:1.2.1'
