### ISSUE TITLE
set max duration

### ISSUE THREAD

**Issue by drsoosmar** [a914-gowtham/android-video-trimmer#50]
hello
tnx for this library because is the best
how can set max duration ?

**Comment by a914-gowtham** [comment]
You can use this. The issue with this is max duration is not restricted by seekbar, done option menu will be disabled if it exceed the max duration and a error toast will be shown  when click option menu. there is a open issue regarding this #34 
```java
TrimVideo.activity(videoUri)
          .setTrimType(TrimType.MIN_MAX_DURATION)
          .setMinToMax(10, 30)  //seconds
          .start(this);
```

**Comment by drsoosmar** [comment]
I mean set max duration to seekbar
