### ISSUE TITLE
Conflictins with exoplayer2.ExoplayerFactory class

### ISSUE THREAD

**Issue by isroilov-sh** [a914-gowtham/android-video-trimmer#53]

**Comment by isroilov-sh** [comment]
after adding dependency to gradle and sync, cant import exoplayer2.ExoplayerFactory to classes.

**Comment by a914-gowtham** [comment]
Hey @isroilov-sh  , i have used ```exoplayer:2.14.0``` in the library. so, exoplayer2.ExoplayerFactory might be changed in the latest version.

**Comment by a914-gowtham** [comment]
@isroilov-sh  Could you try with this ```    implementation 'com.google.android.exoplayer:exoplayer:2.14.1'```

**Comment by a914-gowtham** [comment]
Hi @isroilov-sh , I can reproduce the issue. I've used ```exoplayer:exoplayer:2.14.0```  in the current version of the library.
So, you could try using ``` implementation 'com.google.android.exoplayer:exoplayer:2.14.0'```

Latest version of  ```exoplayer:2.14.1``` will be available in the next release

**Comment by isroilov-sh** [comment]
![DeepinScreenshot_select-area_20210624080943](https://user-images.githubusercontent.com/49440170/123196671-c5f7e180-d4c3-11eb-8304-d17b74930e60.png)
![DeepinScreenshot_select-area_20210624080913](https://user-images.githubusercontent.com/49440170/123196672-c6907800-d4c3-11eb-8bca-f631a95ff87b.png)

**Comment by isroilov-sh** [comment]
when I add implement video-trimmer and make sync project, ExoPlayerFactory become unimportable

**Comment by isroilov-sh** [comment]
![qwe](https://user-images.githubusercontent.com/49440170/123196896-238c2e00-d4c4-11eb-9f6b-f20bfc66b3f3.png)

**Comment by isroilov-sh** [comment]
with video-trimmer 1.4.0 working

**Comment by a914-gowtham** [comment]
I tried removing video-trimmer dependency and kept the exoplayer-2.14.0 .  still, I can't import exoplayerFactory, seems it has been removed from the exoplayer.

**Comment by a914-gowtham** [comment]
Can you try the same? 
1. remove the video-trimmer dependency 
2. try to import exoplayFactory with exoplayer-2.14.0

**Comment by isroilov-sh** [comment]
Just create SimpleExoplayer from SimpleExoplayer.Builder() and removed unimportable ExoplayerFactory class.
