### ISSUE TITLE
Failed to resolve: com.github.a914-gowtham:Android-video-trimmer:1.3.0

### ISSUE THREAD

**Issue by Akhil111993** [a914-gowtham/Android-video-trimmer#6]
I am getting Failed to resolve: com.github.a914-gowtham:Android-video-trimmer:1.3.0 error when trying to use it in gradle

**Comment by a914-gowtham** [comment]
Have you add this line
`allprojects {
	repositories {
		maven { url 'https://jitpack.io' }
	}
}` if you still get this error go to File>Invalidate Caches/Restart
