### ISSUE TITLE
Failed to resolve: com.github.a914-gowtham:android-video-trimmer:1.7.0

### ISSUE THREAD

**Issue by dioob** [a914-gowtham/android-video-trimmer#65]
Yes, my gradle failed to resolve this.

1. I already put "maven {url 'https://jitpack.io'}" in my repo (even on the top)
2. I already did invalidate caches/restart, but still got an error
3. I already did clean project but still

* i got a message "Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0." and when run it it said "Could not find com.github.a914-gowtham:android-video-trimmer:1.7.0."

**Comment by a914-gowtham** [comment]
@dioob  are you using Gradle version 8.0?!

**Comment by dioob** [comment]
> @dioob are you using Gradle version 8.0?!

idk, what about it?

**Comment by dioob** [comment]
i checked in my build gradle dependencies my classpath "com.android.tools.build:gradle:7.0.2"

**Comment by a914-gowtham** [comment]
sample project  is also using `com.android.tools.build:gradle:7.0.2` . can you share the app level and project level build.gradle files?

**Comment by dioob** [comment]
how to check it?

**Comment by dioob** [comment]
oh yeah more, i only have buildscript block with google() and mavenCentral() in my build.gradle, i don't have "allprojects" or "allscripts"

**Comment by a914-gowtham** [comment]
can you check this [build.gradle](https://github.com/a914-gowtham/android-video-trimmer/blob/master/build.gradle) file and try again after adding missed code

**Comment by dioob** [comment]
it seems i fixed it from people in discord.. i need to put  "maven {url 'https://www.jitpack.io'}" INSIDE repositories in settings.gradle, NOT inside build.gradle. here is how it look:

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {url 'https://www.jitpack.io'}
        jcenter() // Warning: this repository is going to shut down soon
    }
}

**Comment by dioob** [comment]
but it has warning said:

[Processor] Library 'C:....aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

**Comment by a914-gowtham** [comment]
yes, you are good to go.

**Comment by dioob** [comment]
alright, thank you

**Comment by a914-gowtham** [comment]
closing the issue. feel free to open an issue anytime
