### ISSUE TITLE
java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: [], 

### ISSUE THREAD

**Issue by khurramconovo** [a914-gowtham/android-video-trimmer#68]
![image](https://user-images.githubusercontent.com/91874597/135817045-83fb8fa9-1d71-43f2-81c0-0a8856248f34.png)

In your library, this function is crashing the application while launching the trimmer in android P. I have tested it on Oneplus mobile phone.

**Comment by khurramconovo** [comment]
![image](https://user-images.githubusercontent.com/91874597/135818943-33654c1a-6c73-43b7-b851-2fea9e3963ec.png)

Even after updating to version 1.7.1, trimmer is crashing on android 30 , samsung as well

**Comment by khurramconovo** [comment]
Please fix this issue by focusing on scoped storage of the android framework.

**Comment by a914-gowtham** [comment]
fixed.
