### ISSUE TITLE
i got error 'FileNotFoundException' when i want to upload trimmed video to firebase storage

### ISSUE THREAD

**Issue by ahmadfma** [a914-gowtham/android-video-trimmer#69]
![c1](https://user-images.githubusercontent.com/56568775/135880024-d13e07fd-d387-43ee-9602-8fecc5424a61.png)

**Comment by Aamir0888** [comment]
val actualUri = Uri.fromFile(File(videoUri.path))

Use like this before uploading video to server. "actualUri" is now final uri for uploading video.
