### ISSUE TITLE
Could not find com.crystal:crystalrangeseekbar:1.1.3.

### ISSUE THREAD

**Issue by MrV3nomous** [a914-gowtham/android-video-trimmer#78]
There are deprecated API in this project

Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.crystal:crystalrangeseekbar:1.1.3.

**Comment by vkfan** [comment]
I got same issue. any update on this?

**Comment by Juanjo3299** [comment]
Add JcCenter repository in build.gradle (app module)

**Comment by a914-gowtham** [comment]
fixed in the [latest version](https://github.com/a914-gowtham/android-video-trimmer/releases/tag/1.7.3) .
