### ISSUE TITLE
Could not find com.crystal:crystalrangeseekbar:1.1.3.

### ISSUE THREAD

**Issue by H28-dev** [a914-gowtham/android-video-trimmer#81]
I've tried adding jcenter, mavenCentral, jitpack.io, but still having this issue.

**Comment by a914-gowtham** [comment]
Hi @H28-dev , Could you reproduce this issue in a dummy project and send me the zip file to me?

**Comment by a914-gowtham** [comment]
Thanks @H28-dev . issue fixed in the [latest version](https://github.com/a914-gowtham/android-video-trimmer/releases/tag/1.7.3) .
