### ISSUE TITLE
protocol not found. "failed to trim"

### ISSUE THREAD

**Issue by angelkoh** [a914-gowtham/android-video-trimmer#96]
I got the following error in the logcat

       E  content://com.android.providers.media.documents/document/video%3A1000022504: Protocol not found
       E  Did you mean file:content://com.android.providers.media.documents/document/video%3A1000022504?

this is what i did:  I pass in the video Uri string to TrimVideo.activity() .

       TrimVideo.activity(it.toString()) .start(this, requestTrimVideo)

I can see the video and I can move the slider around. but after that, when I click the tick to accept the changes, I get the "failed to trim" popup. 

how do I resolve this ?

**Comment by angelkoh** [comment]
it seems to be linked to this stackoverflow issue https://stackoverflow.com/questions/72159779/android-studio-ffmpeg-protocol-not-found

**Comment by a914-gowtham** [comment]
> it seems to be linked to this stackoverflow issue https://stackoverflow.com/questions/72159779/android-studio-ffmpeg-protocol-not-found

@angelkoh will look into it

**Comment by a914-gowtham** [comment]
@angelkoh  and can you try using [v1.7.3](https://github.com/a914-gowtham/android-video-trimmer/releases/tag/1.7.3)

**Comment by angelkoh** [comment]
v1.7.3 works.

**Comment by a914-gowtham** [comment]
@angelkoh  great. removed v1.7.4 changes in v1.7.5
